Lift.create(name: "Back")
Lift.create(name: "Chest")
Lift.create(name: "Biceps")
Lift.create(name: "Triceps")
Lift.create(name: "Lower Body")
Lift.create(name: "Cardio")
Lift.create(name: "Core")

User.create(name: "Tim")
User.create(name: "Alina")
User.create(name: "Chris")